<?xml version="1.0" encoding="UTF-8"?>
<device>
 <name>ADT7410</name>
 <address>0x48</address>
 <registers>
  <register>
   <name>TEMP_MSB</name>
   <address>0x00</address>
   <bitmasks>
    <bitmask>
     <name>sign</name>
     <mask>0x80</mask>
     <access_attr>R</access_attr>
    </bitmask>
    <bitmask>
     <name>temp</name>
     <mask>0x7f</mask>
     <access_attr>R</access_attr>
    </bitmask>
   </bitmasks>
   <byte_access_attr>
    <access_attr>R</access_attr>
    <access_attr>R</access_attr>
    <access_attr>R</access_attr>
    <access_attr>R</access_attr>
    <access_attr>R</access_attr>
    <access_attr>R</access_attr>
    <access_attr>R</access_attr>
    <access_attr>R</access_attr>
   </byte_access_attr>
  </register>
  <register>
   <name>TEMP_LSB</name>
   <address>0x01</address>
   <bitmasks>
    <bitmask>
     <name>temp</name>
     <mask>0xff</mask>
     <access_attr>R</access_attr>
    </bitmask>
   </bitmasks>
   <byte_access_attr>
    <access_attr>R</access_attr>
    <access_attr>R</access_attr>
    <access_attr>R</access_attr>
    <access_attr>R</access_attr>
    <access_attr>R</access_attr>
    <access_attr>R</access_attr>
    <access_attr>R</access_attr>
    <access_attr>R</access_attr>
   </byte_access_attr>
  </register>
  <register>
   <name>STATUS</name>
   <address>0x02</address>
   <bitmasks>
    <bitmask>
     <name>t_low</name>
     <mask>0x10</mask>
     <access_attr>R</access_attr>
    </bitmask>
    <bitmask>
     <name>t_high</name>
     <mask>0x20</mask>
     <access_attr>R</access_attr>
    </bitmask>
    <bitmask>
     <name>t_crit</name>
     <mask>0x40</mask>
     <access_attr>R</access_attr>
    </bitmask>
    <bitmask>
     <name>RDY</name>
     <mask>0x80</mask>
     <access_attr>R</access_attr>
    </bitmask>
   </bitmasks>
   <byte_access_attr>
    <access_attr>N/A</access_attr>
    <access_attr>N/A</access_attr>
    <access_attr>N/A</access_attr>
    <access_attr>N/A</access_attr>
    <access_attr>R</access_attr>
    <access_attr>R</access_attr>
    <access_attr>R</access_attr>
    <access_attr>R</access_attr>
   </byte_access_attr>
  </register>
  <register>
   <name>CONF_REG</name>
   <address>0x03</address>
   <bitmasks>
    <bitmask>
     <name>fault_queue</name>
     <mask>0x03</mask>
     <access_attr>R/W</access_attr>
    </bitmask>
    <bitmask>
     <name>CT_pin_polarity</name>
     <mask>0x04</mask>
     <access_attr>R/W</access_attr>
    </bitmask>
    <bitmask>
     <name>INT_pin_polarity</name>
     <mask>0x08</mask>
     <access_attr>R/W</access_attr>
    </bitmask>
    <bitmask>
     <name>INT/CT_mode</name>
     <mask>0x10</mask>
     <access_attr>R/W</access_attr>
    </bitmask>
    <bitmask>
     <name>operation_mode</name>
     <mask>0x60</mask>
     <access_attr>R/W</access_attr>
    </bitmask>
    <bitmask>
     <name>resolution</name>
     <mask>0x80</mask>
     <access_attr>R/W</access_attr>
    </bitmask>
   </bitmasks>
   <byte_access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
   </byte_access_attr>
  </register>
  <register>
   <name>T_HIGH_MSB</name>
   <address>0x04</address>
   <bitmasks>
    <bitmask>
     <name>temp</name>
     <mask>0xff</mask>
     <access_attr>R/W</access_attr>
    </bitmask>
   </bitmasks>
   <byte_access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
   </byte_access_attr>
  </register>
  <register>
   <name>T_HIGH_LSB</name>
   <address>0x05</address>
   <bitmasks>
    <bitmask>
     <name>temp</name>
     <mask>0xff</mask>
     <access_attr>R/W</access_attr>
    </bitmask>
   </bitmasks>
   <byte_access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
   </byte_access_attr>
  </register>
  <register>
   <name>T_LOW_MSB</name>
   <address>0x06</address>
   <bitmasks>
    <bitmask>
     <name>temp</name>
     <mask>0xff</mask>
     <access_attr>R/W</access_attr>
    </bitmask>
   </bitmasks>
   <byte_access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
   </byte_access_attr>
  </register>
  <register>
   <name>T_LOW_LSB</name>
   <address>0x07</address>
   <bitmasks>
    <bitmask>
     <name>temp</name>
     <mask>0xff</mask>
     <access_attr>R/W</access_attr>
    </bitmask>
   </bitmasks>
   <byte_access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
   </byte_access_attr>
  </register>
  <register>
   <name>T_CRIT_MSB</name>
   <address>0x08</address>
   <bitmasks>
    <bitmask>
     <name>temp</name>
     <mask>0xff</mask>
     <access_attr>R/W</access_attr>
    </bitmask>
   </bitmasks>
   <byte_access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
   </byte_access_attr>
  </register>
  <register>
   <name>T_CRIT_LSB</name>
   <address>0x09</address>
   <bitmasks>
    <bitmask>
     <name>temp</name>
     <mask>0xff</mask>
     <access_attr>R/W</access_attr>
    </bitmask>
   </bitmasks>
   <byte_access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
   </byte_access_attr>
  </register>
  <register>
   <name>ID</name>
   <address>0x0b</address>
   <bitmasks>
    <bitmask>
     <name>revision ID</name>
     <mask>0x07</mask>
     <access_attr>R</access_attr>
    </bitmask>
    <bitmask>
     <name>manufacture ID</name>
     <mask>0xf8</mask>
     <access_attr>R/W</access_attr>
    </bitmask>
   </bitmasks>
   <byte_access_attr>
    <access_attr>R</access_attr>
    <access_attr>R</access_attr>
    <access_attr>R</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
   </byte_access_attr>
  </register>
 </registers>
</device>
