<?xml version="1.0" encoding="UTF-8"?>
<device>
 <name>ADXL3345</name>
 <address>0x34</address>
 <registers>
  <register>
   <name>aaa</name>
   <address>aaa</address>
   <bitmasks>
    <bitmask>
     <name>aaaa</name>
     <mask>0x7</mask>
     <access_attr>R/W</access_attr>
    </bitmask>
    <bitmask>
     <name>bbbb</name>
     <mask>0xe0</mask>
     <access_attr>R/W</access_attr>
    </bitmask>
   </bitmasks>
   <byte_access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
   </byte_access_attr>
  </register>
  <register>
   <name>bbb</name>
   <address>bbb</address>
   <bitmasks>
    <bitmask>
     <name>cccc</name>
     <mask>0xd0</mask>
     <access_attr>R/W</access_attr>
    </bitmask>
    <bitmask>
     <name>dddd</name>
     <mask>0x7</mask>
     <access_attr> W </access_attr>
    </bitmask>
   </bitmasks>
   <byte_access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
   </byte_access_attr>
  </register>
  <register>
   <name>cccc</name>
   <address>cccc</address>
   <bitmasks>
    <bitmask>
     <name>1_bitmask</name>
     <mask>0x3</mask>
     <access_attr>R/W</access_attr>
    </bitmask>
    <bitmask>
     <name>2_bitmask</name>
     <mask>0x1c</mask>
     <access_attr>R/W</access_attr>
    </bitmask>
    <bitmask>
     <name>3_bitmask</name>
     <mask>0xe0</mask>
     <access_attr>R/W</access_attr>
    </bitmask>
   </bitmasks>
   <byte_access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
   </byte_access_attr>
  </register>
  <register>
   <name>ddd</name>
   <address>dddd</address>
   <bitmasks>
    <bitmask>
     <name>bitmask</name>
     <mask>0x1c</mask>
     <access_attr>R/W</access_attr>
    </bitmask>
   </bitmasks>
   <byte_access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
   </byte_access_attr>
  </register>
  <register>
   <name>fsdfds</name>
   <address>dsfsdfsd</address>
   <bitmasks>
    <bitmask>
     <name>ewrwerwer</name>
     <mask>0x2a</mask>
     <access_attr>R/W</access_attr>
    </bitmask>
   </bitmasks>
   <byte_access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
   </byte_access_attr>
  </register>
  <register>
   <name>eeee</name>
   <address>eeeee</address>
   <bitmasks>
    <bitmask>
     <name>BITMASK</name>
     <mask>0xf0</mask>
     <access_attr>R/W</access_attr>
    </bitmask>
   </bitmasks>
   <byte_access_attr>
    <access_attr>N/A</access_attr>
    <access_attr>N/A</access_attr>
    <access_attr>N/A</access_attr>
    <access_attr>N/A</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
    <access_attr>R/W</access_attr>
   </byte_access_attr>
  </register>
 </registers>
</device>
