# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiRegisterForm.ui'
#
# Created: Fri Nov 28 16:35:59 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_RegitersForm(object):
    def setupUi(self, RegitersForm):
        RegitersForm.setObjectName("RegitersForm")
        RegitersForm.resize(695, 457)
        self.registersWidget = QtGui.QTableWidget(RegitersForm)
        self.registersWidget.setGeometry(QtCore.QRect(40, 100, 261, 251))
        self.registersWidget.setObjectName("registersWidget")
        self.registersWidget.setColumnCount(0)
        self.registersWidget.setRowCount(0)
        self.horizontalLayoutWidget = QtGui.QWidget(RegitersForm)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 40, 541, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.deviceNameLabel = QtGui.QLabel(self.horizontalLayoutWidget)
        self.deviceNameLabel.setObjectName("deviceNameLabel")
        self.horizontalLayout.addWidget(self.deviceNameLabel)
        self.deviceNameTextEdit = QtGui.QTextEdit(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deviceNameTextEdit.sizePolicy().hasHeightForWidth())
        self.deviceNameTextEdit.setSizePolicy(sizePolicy)
        self.deviceNameTextEdit.setMinimumSize(QtCore.QSize(7, 5))
        self.deviceNameTextEdit.setMaximumSize(QtCore.QSize(1677, 1677))
        self.deviceNameTextEdit.setFrameShadow(QtGui.QFrame.Plain)
        self.deviceNameTextEdit.setObjectName("deviceNameTextEdit")
        self.horizontalLayout.addWidget(self.deviceNameTextEdit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.addressLabel = QtGui.QLabel(self.horizontalLayoutWidget)
        self.addressLabel.setObjectName("addressLabel")
        self.horizontalLayout.addWidget(self.addressLabel)
        self.addressTextEdit = QtGui.QTextEdit(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addressTextEdit.sizePolicy().hasHeightForWidth())
        self.addressTextEdit.setSizePolicy(sizePolicy)
        self.addressTextEdit.setMinimumSize(QtCore.QSize(7, 5))
        self.addressTextEdit.setMaximumSize(QtCore.QSize(1677, 1677))
        self.addressTextEdit.setFrameShadow(QtGui.QFrame.Plain)
        self.addressTextEdit.setObjectName("addressTextEdit")
        self.horizontalLayout.addWidget(self.addressTextEdit)
        spacerItem1 = QtGui.QSpacerItem(200, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.saveButton = QtGui.QPushButton(RegitersForm)
        self.saveButton.setGeometry(QtCore.QRect(470, 380, 75, 23))
        self.saveButton.setObjectName("saveButton")
        self.cancelButton = QtGui.QPushButton(RegitersForm)
        self.cancelButton.setGeometry(QtCore.QRect(580, 380, 75, 23))
        self.cancelButton.setObjectName("cancelButton")
        self.frame = QtGui.QFrame(RegitersForm)
        self.frame.setGeometry(QtCore.QRect(310, 100, 371, 251))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 46, 13))
        self.label.setObjectName("label")
        self.nameOfRegLabel = QtGui.QLabel(self.frame)
        self.nameOfRegLabel.setGeometry(QtCore.QRect(40, 0, 61, 16))
        self.nameOfRegLabel.setText("")
        self.nameOfRegLabel.setObjectName("nameOfRegLabel")
        self.Reg8BitValuePlainTextEdit = QtGui.QPlainTextEdit(self.frame)
        self.Reg8BitValuePlainTextEdit.setGeometry(QtCore.QRect(70, 100, 104, 31))
        self.Reg8BitValuePlainTextEdit.setObjectName("Reg8BitValuePlainTextEdit")
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 61, 31))
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 371, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.register8BitHLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.register8BitHLayout.setContentsMargins(0, 0, 0, 0)
        self.register8BitHLayout.setObjectName("register8BitHLayout")
        self.createBitmaskButton = QtGui.QPushButton(self.frame)
        self.createBitmaskButton.setGeometry(QtCore.QRect(230, 100, 131, 31))
        self.createBitmaskButton.setObjectName("createBitmaskButton")
        self.horizontalLayoutWidget_3 = QtGui.QWidget(RegitersForm)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(40, 80, 541, 22))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.registersLabel = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.registersLabel.setObjectName("registersLabel")
        self.horizontalLayout_4.addWidget(self.registersLabel)
        self.bitmaskLabelTitle = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.bitmaskLabelTitle.setObjectName("bitmaskLabelTitle")
        self.horizontalLayout_4.addWidget(self.bitmaskLabelTitle)
        spacerItem2 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.addRegisterButton = QtGui.QPushButton(RegitersForm)
        self.addRegisterButton.setGeometry(QtCore.QRect(50, 362, 241, 41))
        self.addRegisterButton.setObjectName("addRegisterButton")

        self.retranslateUi(RegitersForm)
        QtCore.QMetaObject.connectSlotsByName(RegitersForm)

    def retranslateUi(self, RegitersForm):
        RegitersForm.setWindowTitle(QtGui.QApplication.translate("RegitersForm", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.deviceNameLabel.setText(QtGui.QApplication.translate("RegitersForm", "Device name:", None, QtGui.QApplication.UnicodeUTF8))
        self.addressLabel.setText(QtGui.QApplication.translate("RegitersForm", "7 bit Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("RegitersForm", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("RegitersForm", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("RegitersForm", "REG: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("RegitersForm", "Reg Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.createBitmaskButton.setText(QtGui.QApplication.translate("RegitersForm", "Create_Bitmask", None, QtGui.QApplication.UnicodeUTF8))
        self.registersLabel.setText(QtGui.QApplication.translate("RegitersForm", "Registers:", None, QtGui.QApplication.UnicodeUTF8))
        self.bitmaskLabelTitle.setText(QtGui.QApplication.translate("RegitersForm", "Bitmasks:", None, QtGui.QApplication.UnicodeUTF8))
        self.addRegisterButton.setText(QtGui.QApplication.translate("RegitersForm", "Add Register", None, QtGui.QApplication.UnicodeUTF8))

