# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiRegistersView.ui'
#
# Created: Sun Dec  7 16:27:10 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_RegistersView(object):
    def setupUi(self, RegistersView):
        RegistersView.setObjectName("RegistersView")
        RegistersView.resize(754, 599)
        self.RegistersTable = QtGui.QTableWidget(RegistersView)
        self.RegistersTable.setGeometry(QtCore.QRect(0, 130, 421, 391))
        self.RegistersTable.setObjectName("RegistersTable")
        self.RegistersTable.setColumnCount(4)
        self.RegistersTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.RegistersTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.RegistersTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.RegistersTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.RegistersTable.setHorizontalHeaderItem(3, item)
        self.FormulasTable = QtGui.QTableWidget(RegistersView)
        self.FormulasTable.setGeometry(QtCore.QRect(430, 130, 321, 391))
        self.FormulasTable.setObjectName("FormulasTable")
        self.FormulasTable.setColumnCount(3)
        self.FormulasTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.FormulasTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.FormulasTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.FormulasTable.setHorizontalHeaderItem(2, item)
        self.AddFormulaButton = QtGui.QPushButton(RegistersView)
        self.AddFormulaButton.setGeometry(QtCore.QRect(500, 80, 181, 31))
        self.AddFormulaButton.setObjectName("AddFormulaButton")
        self.FormulaText = QtGui.QPlainTextEdit(RegistersView)
        self.FormulaText.setGeometry(QtCore.QRect(440, 20, 301, 51))
        self.FormulaText.setObjectName("FormulaText")
        self.UpdateRegisterButton = QtGui.QPushButton(RegistersView)
        self.UpdateRegisterButton.setGeometry(QtCore.QRect(320, 90, 101, 31))
        self.UpdateRegisterButton.setObjectName("UpdateRegisterButton")
        self.RegBit1 = QtGui.QPushButton(RegistersView)
        self.RegBit1.setGeometry(QtCore.QRect(250, 50, 31, 31))
        self.RegBit1.setObjectName("RegBit1")
        self.RegBit2 = QtGui.QPushButton(RegistersView)
        self.RegBit2.setGeometry(QtCore.QRect(210, 50, 31, 31))
        self.RegBit2.setObjectName("RegBit2")
        self.RegBit3 = QtGui.QPushButton(RegistersView)
        self.RegBit3.setGeometry(QtCore.QRect(170, 50, 31, 31))
        self.RegBit3.setObjectName("RegBit3")
        self.RegBit4 = QtGui.QPushButton(RegistersView)
        self.RegBit4.setGeometry(QtCore.QRect(130, 50, 31, 31))
        self.RegBit4.setObjectName("RegBit4")
        self.RegBit5 = QtGui.QPushButton(RegistersView)
        self.RegBit5.setGeometry(QtCore.QRect(90, 50, 31, 31))
        self.RegBit5.setObjectName("RegBit5")
        self.RegBit6 = QtGui.QPushButton(RegistersView)
        self.RegBit6.setGeometry(QtCore.QRect(50, 50, 31, 31))
        self.RegBit6.setObjectName("RegBit6")
        self.RegBit7 = QtGui.QPushButton(RegistersView)
        self.RegBit7.setGeometry(QtCore.QRect(10, 50, 31, 31))
        self.RegBit7.setObjectName("RegBit7")
        self.RegBit0 = QtGui.QPushButton(RegistersView)
        self.RegBit0.setGeometry(QtCore.QRect(290, 50, 31, 31))
        self.RegBit0.setObjectName("RegBit0")

        self.retranslateUi(RegistersView)
        QtCore.QMetaObject.connectSlotsByName(RegistersView)

    def retranslateUi(self, RegistersView):
        RegistersView.setWindowTitle(QtGui.QApplication.translate("RegistersView", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.RegistersTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("RegistersView", "Number", None, QtGui.QApplication.UnicodeUTF8))
        self.RegistersTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("RegistersView", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.RegistersTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("RegistersView", "Hex Value", None, QtGui.QApplication.UnicodeUTF8))
        self.RegistersTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("RegistersView", "Function set", None, QtGui.QApplication.UnicodeUTF8))
        self.FormulasTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("RegistersView", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.FormulasTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("RegistersView", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.FormulasTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("RegistersView", "Formula", None, QtGui.QApplication.UnicodeUTF8))
        self.AddFormulaButton.setText(QtGui.QApplication.translate("RegistersView", "Add new formula", None, QtGui.QApplication.UnicodeUTF8))
        self.UpdateRegisterButton.setText(QtGui.QApplication.translate("RegistersView", "Update register", None, QtGui.QApplication.UnicodeUTF8))
        self.RegBit1.setText(QtGui.QApplication.translate("RegistersView", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.RegBit2.setText(QtGui.QApplication.translate("RegistersView", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.RegBit3.setText(QtGui.QApplication.translate("RegistersView", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.RegBit4.setText(QtGui.QApplication.translate("RegistersView", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.RegBit5.setText(QtGui.QApplication.translate("RegistersView", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.RegBit6.setText(QtGui.QApplication.translate("RegistersView", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.RegBit7.setText(QtGui.QApplication.translate("RegistersView", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.RegBit0.setText(QtGui.QApplication.translate("RegistersView", "0", None, QtGui.QApplication.UnicodeUTF8))

